---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: iotedge
  namespace: iotedge
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  helmVersion: v3
  chart:
    repository: https://edgek8s.blob.core.windows.net/staging
    name: edge-kubernetes
    version: 0.2.1
  valuesFrom:
    - secretKeyRef:
        name: dcs
