---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: iotedge-crd
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: edge-crd
  helmVersion: v3
  chart:
    repository: https://jiria.github.io/jdemo-helm
    name: edge-kubernetes-crd
    version: 0.1.7